name: eend
channels:
  - defaults
dependencies:
  - python=3.7
  - conda-forge::cudatoolkit=10.0
  - pip
  - pip:
    - h5py
    - librosa==0.9.1
    - numpy
    - protobuf
    - scipy
    - tqdm
    - SoundFile
    - matplotlib
    - kaldiio
    - yamlargparse
    - intervaltree
    - tabulate==0.9.0
